spring:
  datasource:
    url: jdbc:mysql://mysql:3306/easy_learning
#    url: jdbc:mysql://localhost:2020/easy_learning
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
#    open-in-view: false
  application:
    name: easy_learning
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 30
    refresh: 300
