spring:
  datasource:
    url: jdbc:mysql://mysql:3306/easy_learning
#    url: jdbc:mysql://localhost:1212/easy_learning
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  application:
    name: easy_learning
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  security:
    user:
      name: admin
      password: $2a$12$HXd78PaHX.RUjzLhRTaLquTW2HzskPCm7Doq3RUXBsiQ0wCgT3iZW
